# Generated by Django 6.0.6 on 2026-06-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEmprendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Número de cédula o documento de identidad')),
                ('nombres_apellidos', models.CharField(max_length=200, verbose_name='Nombres y apellidos completos')),
                ('edad', models.PositiveSmallIntegerField(verbose_name='Edad')),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('no_responde', 'Prefiero no responder')], max_length=20, verbose_name='Sexo')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='Número de WhatsApp')),
                ('vinculacion', models.CharField(choices=[('estudiante', 'Estudiante de UNEMI'), ('retirado', 'Retirado UNEMI'), ('graduado', 'Graduado(a) de UNEMI'), ('docente', 'Docente de UNEMI'), ('administrativo', 'Personal administrativo de UNEMI'), ('externo', 'Externo'), ('otro', 'Otro')], max_length=20, verbose_name='Vínculo con UNEMI')),
                ('correo_institucional', models.EmailField(blank=True, help_text='Requerido para estudiantes, docentes y personal administrativo', max_length=254, null=True, verbose_name='Correo institucional UNEMI')),
                ('correo_personal', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico personal')),
                ('carrera_actual', models.CharField(blank=True, help_text='Solo para estudiantes', max_length=200, null=True, verbose_name='Carrera que cursa actualmente')),
                ('semestre_actual', models.CharField(blank=True, help_text='Solo para estudiantes', max_length=20, null=True, verbose_name='Semestre actual')),
                ('carrera_graduado', models.CharField(blank=True, help_text='Solo para graduados', max_length=200, null=True, verbose_name='Carrera de la que se graduó')),
                ('provincia', models.CharField(max_length=100, verbose_name='Provincia de residencia')),
                ('canton', models.CharField(max_length=100, verbose_name='Cantón o ciudad de residencia')),
                ('nombre_emprendimiento', models.CharField(max_length=200, verbose_name='Nombre del emprendimiento o negocio')),
                ('descripcion_productos', models.TextField(verbose_name='Descripción de productos o servicio principal')),
                ('categoria', models.CharField(choices=[('gastronomia', 'Gastronomía'), ('comercio', 'Comercio'), ('servicios', 'Servicios'), ('tecnologia', 'Tecnología'), ('artesanias', 'Artesanías'), ('agricultura', 'Agricultura'), ('belleza', 'Belleza y bienestar'), ('educacion', 'Educación'), ('textil', 'Textil y confección'), ('turismo', 'Turismo'), ('otro', 'Otro')], max_length=20, verbose_name='Categoría principal del emprendimiento')),
                ('categoria_otro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Especifique la categoría (si eligió Otro)')),
                ('tiempo_funcionamiento', models.CharField(choices=[('idea', 'Idea de negocio'), ('menos_6m', 'Menos de 6 meses'), ('6m_1a', 'De 6 meses a 1 año'), ('1a_3a', 'De 1 a 3 años'), ('mas_3a', 'Más de 3 años')], max_length=20, verbose_name='Tiempo de funcionamiento del emprendimiento')),
                ('numero_colaboradores', models.CharField(choices=[('ninguno', 'Ninguno (Solo yo)'), ('1_2', '1 a 2 personas'), ('3_5', '3 a 5 personas'), ('6_9', '6 a 9 personas'), ('mas_10', 'Más de 10 personas')], max_length=10, verbose_name='Número de colaboradores o empleados')),
                ('direccion', models.CharField(max_length=300, verbose_name='Dirección del emprendimiento')),
                ('redes_sociales', models.TextField(verbose_name='Redes sociales del emprendimiento')),
                ('tiene_ruc', models.BooleanField(verbose_name='¿Cuenta con RUC o RIMPE?')),
                ('numero_ruc', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de RUC o RIMPE')),
                ('archivo_ruc', models.FileField(blank=True, null=True, upload_to='ruc/', verbose_name='RUC o RIMPE adjunto')),
                ('permisos_funcionamiento', models.CharField(choices=[('si', 'Sí'), ('no', 'No'), ('en_tramite', 'En trámite')], max_length=20, verbose_name='¿Cuenta con permisos de funcionamiento?')),
                ('archivo_permiso', models.FileField(blank=True, null=True, upload_to='permisos/', verbose_name='Permiso de funcionamiento adjunto')),
                ('capacitacion_intereses', models.JSONField(default=list, help_text='Lista con uno o más valores de CapacitacionChoices', verbose_name='Temas de capacitación de interés')),
                ('capacitacion_otro', models.CharField(blank=True, max_length=200, null=True, verbose_name='Otro tema de capacitación (detallar)')),
                ('participo_anteriormente', models.BooleanField(null=True, verbose_name='¿Ha participado en actividades de la Gestión de Emprendimiento UNEMI?')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios, sugerencias o expectativas')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Registro de Emprendedor',
                'verbose_name_plural': 'Registros de Emprendedores',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
